import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background text-foreground`}>
        <header className="border-b">
          <nav className="max-w-4xl mx-auto px-4 py-3 flex gap-4">
            <a href="/" className="font-semibold">Mezkenz Fitness</a>
            <a href="/workouts" className="opacity-80 hover:opacity-100">Workouts</a>
            <a href="/vitals" className="opacity-80 hover:opacity-100">Vitals</a>
            <a href="/mbti" className="opacity-80 hover:opacity-100">MBTI</a>
          </nav>
        </header>
        <main className="max-w-4xl mx-auto px-4 py-6">
          {children}
        </main>
      </body>
    </html>
  );
}
