import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy",
  description: "How Atlas IT Solutions handles personal data and operational information.",
  alternates: {
    canonical: "/privacy"
  }
};

export default function PrivacyPage() {
  return (
    <article className="max-w-3xl space-y-6 pb-24 text-base leading-relaxed text-slate-600">
      <header className="space-y-3">
        <h1 className="text-4xl font-bold text-secondary">Privacy Notice</h1>
        <p>
          Atlas IT Solutions processes limited personal information to deliver managed IT services and respond to customer inquiries.
          We retain contact details only for as long as required to provide support, and we never sell customer data.
        </p>
      </header>
      <section className="space-y-3">
        <h2 className="text-2xl font-semibold text-secondary">What we collect</h2>
        <ul className="list-disc space-y-2 pl-6">
          <li>Contact information provided via forms or support tickets.</li>
          <li>Device metadata required for endpoint monitoring and patching.</li>
          <li>Security telemetry generated by managed protection tools.</li>
        </ul>
      </section>
      <section className="space-y-3">
        <h2 className="text-2xl font-semibold text-secondary">Your rights</h2>
        <p>
          Customers can request data access, correction, or deletion at any time by emailing privacy@atlasitsolutions.example. We respond within 30 days.
        </p>
      </section>
    </article>
  );
}
